version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://toretto.id.vn:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - MONGODB_URI=your_mongodb_connection_string
    volumes:
      - ./server/payslips:/app/payslips
      - ./server/payslip-template:/app/payslip-template
