version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: salary-frontend
    restart: always
    networks:
      - app-network
    # Memory limits to prevent heap issues
    deploy:
      resources:
        limits:
          memory: 256M

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: salary-backend
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGODB_URI=mongodb://localhost:27017/salary-calculator
      - CORS_ORIGIN=https://toretto.id.vn
    volumes:
      - ./server/payslips:/app/payslips
      - ./server/payslip-template:/app/payslip-template
    restart: always
    networks:
      - app-network
    # Memory limits to prevent heap issues
    deploy:
      resources:
        limits:
          memory: 256M

  nginx:
    image: nginx:alpine
    container_name: salary-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - app-network
    # Memory limits to prevent heap issues
    deploy:
      resources:
        limits:
          memory: 128M

  # Optional service for SSL certificate management
  certbot:
    image: certbot/certbot
    container_name: salary-certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - nginx

networks:
  app-network:
    driver: bridge
