version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # - REACT_APP_API_URL=http://18.142.219.52:5000/api
      - NODE_ENV=production
    restart: always

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGODB_URI=mongodb://localhost:27017/salary-calculator
      - CORS_ORIGIN=http://18.142.219.52:3000,http://18.142.219.52,http://localhost:3000,http://localhost
    volumes:
      - ./server/payslips:/app/payslips
      - ./server/payslip-template:/app/payslip-template
    restart: always

networks:
  default:
    driver: bridge
